# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35402d95491c8ceddb2fd2169e31c7bbcade407f1adbb9594d6e5ee620477ebd60638c8e56dd2044db1bdba6b86b4d43cc3eef3a38a8ce0e1407e78a9050772f

test:
  secret_key_base: 1a150be1a8bc6aac9c9f6d36aae489e447474865dcd119be3877e028d7fabe883f0d118cd7fd7103e9b0d97b03753c566ec4ccfcc26bf0d38748201bd0d261de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
